Added TitleId to TitlePlayerAccount Entity and loads its on creation …
Annonator/PlayFabBuddy pull request #60
Opened 2022-02-13 13:37 UTC by Annonator

…to Fix #56

2022-02-13 20:11 UTC, Structed requested changes
I think teh change in semantics is not correct. Please check.
Otherwise, looks good

2022-02-13 20:11 UTC, Structed commented on src/PlayFabBuddy.Infrastructure/Adapter/PlayFab/PlayerAccountAdapter.cs
> +        //var playedTitleList = await GetPlayedTitleList(account);
remove comment

2022-02-13 20:11 UTC, Structed commented on src/PlayFabBuddy.Infrastructure/Adapter/PlayFab/PlayerAccountAdapter.cs
> +        if (!account.HasOneTitlePlayerAccount())
Did you change semantics here on purpose? It was supposed to be `tiles > 1` instead of `titles == 1`

2022-02-13 20:11 UTC, Structed commented on src/PlayFabBuddy.Lib/Aggregate/MasterPlayerAccountAggregate.cs
> +    public bool HasOneTitlePlayerAccount()
See above - why changed to checking for exactly one and not more than one?

2022-02-13 20:11 UTC, Structed commented on src/PlayFabBuddy.Infrastructure/Adapter/PlayFab/PlayerAccountAdapter.cs
> +        if (!account.HasOneTitlePlayerAccount())
Also, this will throw the excepton if tehre is less than one title involved...

2022-02-14 07:41 UTC, Annonator commented
> I think teh change in semantics is not correct. Please check. Otherwise, looks good

Reverted back to intial semantics and merged it :). thanks for the review!

2022-02-14 07:41 UTC, merged